language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
cache:
  directories:
    - $HOME/.julia/artifacts
notifications:
  email: false
codecov: true
coveralls: true
